from fastapi import APIRouter, Request
from DB_CONNECTION import DB_CONNECTION_GET

ROUTER_P_CLIENT_VIOLINIST_INS = APIRouter()

@ROUTER_P_CLIENT_VIOLINIST_INS.post("/P_CLIENT_VIOLINIST_INS")
async def P_CLIENT_VIOLINIST_INS_HANDLER(REQUEST: Request):
    BODY = await REQUEST.json()
    DEVICE_ID = BODY.get("DEVICE_ID")
    IP_ADDRESS = BODY.get("IP_ADDRESS")
    LATITUDE = BODY.get("LATITUDE")
    LONGITUDE = BODY.get("LONGITUDE")

    CONNECTION = DB_CONNECTION_GET()
    CURSOR = CONNECTION.cursor()

    CURSOR.execute("""
        DECLARE @VIOLINIST_ID INT;
        EXEC P_CLIENT_VIOLINIST_INS
            @DEVICE_ID=?,
            @IP_ADDRESS=?,
            @LATITUDE=?,
            @LONGITUDE=?,
            @VIOLINIST_ID=@VIOLINIST_ID OUTPUT;
        SELECT @VIOLINIST_ID AS VIOLINIST_ID;
    """, (DEVICE_ID, IP_ADDRESS, LATITUDE, LONGITUDE))

    RESULT = CURSOR.fetchone()
    CURSOR.close()
    CONNECTION.close()

    return {"P_CLIENT_VIOLINIST_INS": RESULT.VIOLINIST_ID if RESULT else None}
